Repository LouisBenjamin/UC3-Team-Project, pull requests merged in 2019-02, with the labels that each got.

#29 Harish jayasankar
  assets/css/style-complete.css
  assets/images/background.jpg
  core/classes/user.php
  core/database/connection.php
  core/init.php
  includes/login.php
  includes/signup.php
  index.php
Labels: Task, back-end, front-end

#36 Fixed Connection to Database, Bootstrap + Jquery, Test Script + typo fixes
  LBDtest.cmd
  assets/css/bootstrap-grid.css
  assets/css/bootstrap-grid.css.map
  assets/css/bootstrap-grid.min.css
  assets/css/bootstrap-grid.min.css.map
  assets/css/bootstrap-reboot.css
  assets/css/bootstrap-reboot.css.map
  assets/css/bootstrap-reboot.min.css
  assets/css/bootstrap-reboot.min.css.map
  assets/css/bootstrap.css
  assets/css/bootstrap.css.map
  assets/css/bootstrap.min.css
  assets/css/bootstrap.min.css.map
  assets/css/font-awesome.css
  assets/css/login.css
  assets/images/montreal.jpg
  assets/js/bootstrap.bundle.js
  assets/js/bootstrap.bundle.js.map
  assets/js/bootstrap.bundle.min.js
  assets/js/bootstrap.bundle.min.js.map
  assets/js/bootstrap.js
  assets/js/bootstrap.js.map
  assets/js/bootstrap.min.js
  assets/js/bootstrap.min.js.map
  assets/js/jquery.min.js
  core/database/connection.php
  home.php
  index.php
  login.php
Labels: High Priority

#42 Tato class starting point #41
  README.md
  core/classes/tato.php
  core/classes/user.php
  core/init.php
  home.php
Labels: 1-point, back-end
